// Netscape cookie-file format helpers shared by the export (refresh) and
// import (bootstrap) paths — see https://curl.se/docs/http-cookies.html.

function toNetscapeFormat(cookies) {
  const relevant = cookies.filter((c) => /(^|\.)youtube\.com$|(^|\.)google\.com$/.test(c.domain));
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by cookie-refresher — do not edit by hand',
    '',
  ];
  for (const c of relevant) {
    const domain = c.domain;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathField = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
    lines.push([domain, includeSubdomains, pathField, secure, expiry, c.name, c.value].join('\t'));
  }
  return lines.join('\n') + '\n';
}

// Parses a Netscape-format cookies.txt (the same format the user already
// exports today via a browser extension per clip-studio/deploy/README.md
// §4) into Playwright's `context.addCookies()` input shape.
function parseNetscapeCookies(text) {
  const cookies = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const parts = line.split('\t');
    if (parts.length < 7) continue;
    const [domain, , pathField, secureFlag, expiry, name, ...valueParts] = parts;
    const value = valueParts.join('\t');
    const expires = Number(expiry) > 0 ? Number(expiry) : -1;
    cookies.push({
      name,
      value,
      domain,
      path: pathField || '/',
      secure: secureFlag === 'TRUE',
      expires,
    });
  }
  return cookies;
}

module.exports = { toNetscapeFormat, parseNetscapeCookies };
